// recoveryquest (16)/Practice/games/rehearsal/scenarios.ts
import { Scenario } from "./types";

export const SCENARIO_001_INVITATION: Scenario = {
  id: "scenario_001_invitation",
  title: "Scenario 001 — The Invitation",
  context: "friend",
  clinicalTargets: ["refusal", "boundaries", "distress_tolerance", "defusion"],
  difficulty: 1,
  entryBeatId: "beat_1",
  tags: ["boundary", "peer_pressure", "unit:cravings"],
  successConditions: [{ type: "maintain_boundary" }, { type: "exit_safe" }],
  beats: {
    beat_1: {
      id: "beat_1",
      speaker: "npc",
      text: "Yo! We’re all heading out. Come grab a drink—just one.",
      pressure: 2,
      tags: ["peer_pressure", "alcohol", "minimization"],
      choices: [
        {
          id: "c1",
          label: "No thanks, I’m not drinking.",
          style: "firm",
          efficacy: 5,
          composureDelta: +2,
          consequenceText: "Friend: “Alright… you sure?”",
          nextBeatId: "beat_4_safe_boundary",
          teaches: "broken_record_no",
        },
        {
          id: "c2",
          label: "I’m good tonight.",
          style: "soft",
          efficacy: 4,
          composureDelta: 0,
          consequenceText: "Friend leans in, trying again.",
          nextBeatId: "beat_2_push",
        },
        {
          id: "c3",
          label: "Maybe later.",
          style: "avoid",
          efficacy: 2,
          composureDelta: -2,
          consequenceText: "Friend hears a door left open—and pushes.",
          nextBeatId: "beat_2_push",
        },
        {
          id: "c4",
          label: "Sure, why not.",
          style: "appease",
          efficacy: 1,
          composureDelta: -6,
          consequenceText: "Friend: “That’s what I’m talking about!”",
          nextBeatId: "beat_4_unsafe",
        },
      ],
    },

    beat_2_push: {
      id: "beat_2_push",
      speaker: "npc",
      text: "C’mon, don’t be boring. You’ve been good for weeks.",
      pressure: 3,
      tags: ["mockery", "permission", "earned"],
      toolOffer: {
        allowedTools: ["box_breath", "defusion"],
        reason: "Your body is starting to react. Regulate before responding.",
        composureRestore: 8,
      },
      choices: [
        {
          id: "c1",
          label: "I said no. Don’t offer again.",
          style: "firm",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "Friend: “Okay, okay. I hear you.”",
          nextBeatId: "beat_3_guilt",
          teaches: "boundary_reinforcement",
        },
        {
          id: "c2",
          label: "I’m serious about this.",
          style: "firm",
          efficacy: 4,
          composureDelta: +1,
          consequenceText: "Friend pauses, then tries a different angle.",
          nextBeatId: "beat_3_guilt",
        },
        {
          id: "c3",
          label: "Relax, I’m fine.",
          style: "appease",
          efficacy: 2,
          composureDelta: -4,
          consequenceText: "Friend: “See? Then it won’t hurt.”",
          nextBeatId: "beat_3_guilt",
          teaches: "minimization_trap",
        },
        {
          id: "c4",
          label: "Why are you pushing me?",
          style: "attack",
          efficacy: 2,
          composureDelta: -3,
          consequenceText: "Friend gets defensive. Pressure rises.",
          nextBeatId: "beat_3_guilt",
        },
      ],
    },

    beat_3_guilt: {
      id: "beat_3_guilt",
      speaker: "npc",
      text: "Wow. After everything we’ve been through?",
      pressure: 4,
      tags: ["guilt", "emotional_hook"],
      toolOffer: {
        allowedTools: ["defusion", "play_tape"],
        reason: "This is a guilt hook. Pause before answering.",
        composureRestore: 10,
      },
      choices: [
        {
          id: "c1",
          label: "I care about you. I’m still not drinking.",
          style: "regulated",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "Friend exhales. The heat drops.",
          nextBeatId: "beat_4_safe_boundary",
          teaches: "repair_without_collapse",
        },
        {
          id: "c2",
          label: "This isn’t about you.",
          style: "firm",
          efficacy: 4,
          composureDelta: +1,
          consequenceText: "Friend backs off… a little.",
          nextBeatId: "beat_4_exit_prompt",
        },
        {
          id: "c3",
          label: "Fine. Just one.",
          style: "appease",
          efficacy: 1,
          composureDelta: -8,
          consequenceText: "Friend smiles. Risk spikes.",
          nextBeatId: "beat_4_unsafe",
        },
        {
          id: "c4",
          label: "Whatever.",
          style: "avoid",
          efficacy: 2,
          composureDelta: -4,
          consequenceText: "Friend reads it as permission to keep pushing.",
          nextBeatId: "beat_4_exit_prompt",
        },
      ],
    },

    beat_4_exit_prompt: {
      id: "beat_4_exit_prompt",
      speaker: "system",
      text: "You can end this safely. Leaving early is not failure—it’s skill.",
      pressure: 3,
      tags: ["exit", "safety"],
      choices: [
        {
          id: "c1",
          label: "I’m heading out. Catch you later.",
          style: "exit",
          efficacy: 5,
          composureDelta: +2,
          consequenceText: "You leave before the situation sharpens.",
          nextBeatId: "beat_4_safe_exit",
          teaches: "exit_with_dignity",
        },
        {
          id: "c2",
          label: "I’ll stay, but I’m not drinking.",
          style: "firm",
          efficacy: 4,
          composureDelta: 0,
          consequenceText: "You stay anchored. The boundary is clear.",
          nextBeatId: "beat_4_safe_boundary",
        },
      ],
    },

    beat_4_safe_boundary: {
      id: "beat_4_safe_boundary",
      speaker: "system",
      text: "SAFE RESOLUTION — Boundary Held.\nYou held your boundary under pressure.",
      pressure: 2,
      tags: ["safe_end", "boundary"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Reinforce the Boundary",
        options: [
          'Text someone you trust: “I said no today.”',
          "Write your go-to refusal line and save it.",
          "Avoid one high-risk place tonight.",
        ],
      },
    },

    beat_4_safe_exit: {
      id: "beat_4_safe_exit",
      speaker: "system",
      text: "SAFE RESOLUTION — Exit With Dignity.\nLeaving early is skill, not weakness.",
      pressure: 2,
      tags: ["safe_end", "exit"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Lock In the Win",
        options: [
          "Take a 5-minute walk to downshift.",
          "Drink water + eat something simple.",
          "Send a quick check-in to a support person.",
        ],
      },
    },

    beat_4_unsafe: {
      id: "beat_4_unsafe",
      speaker: "system",
      text: "UNSAFE RESOLUTION — Engagement.\nThis path increases relapse risk.\nNo shame. Pivot now.",
      pressure: 4,
      tags: ["unsafe_end", "appease", "permission"],
      isEnd: true,
      endType: "unsafe",
      applyQuest: {
        title: "Interrupt the Slide",
        options: [
          "Pause 60 seconds and breathe.",
          "Use a grounding tool now.",
          "Reach out before making another decision.",
        ],
      },
    },
  },
};

export const SCENARIO_002_DEALER_TEXT: Scenario = {
  id: "scenario_002_dealer_text",
  title: "Scenario 002 — The Dealer Text",
  context: "dealer",
  clinicalTargets: ["impulse_control", "delay", "defusion", "access_management"],
  difficulty: 2,
  entryBeatId: "beat_1",
  tags: ["impulse_control", "access_management", "unit:cravings"],
  successConditions: [{ type: "exit_safe" }, { type: "use_tool_then_choose" }],
  beats: {
    beat_1: {
      id: "beat_1",
      speaker: "system",
      text: "Buzz.\n“Yo. You good? I’m around.”",
      pressure: 3,
      tags: ["impulse", "availability", "access"],
      choices: [
        {
          id: "c1",
          label: "Ignore the text.",
          style: "exit",
          efficacy: 5,
          composureDelta: +2,
          consequenceText: "You don’t feed the spike.",
          nextBeatId: "beat_2_mind_speaks",
        },
        {
          id: "c2",
          label: "Block the number.",
          style: "firm",
          efficacy: 5,
          composureDelta: +4,
          consequenceText: "Access removed. The urge loses fuel.",
          nextBeatId: "beat_4_safe_access_cut",
          teaches: "contact_hygiene",
        },
        {
          id: "c3",
          label: "Not interested.",
          style: "firm",
          efficacy: 4,
          composureDelta: +1,
          consequenceText: "You respond—but leave the door cracked.",
          nextBeatId: "beat_2_mind_speaks",
        },
        {
          id: "c4",
          label: "What do you have?",
          style: "appease",
          efficacy: 1,
          composureDelta: -8,
          consequenceText: "Engagement spikes urgency and rumination.",
          nextBeatId: "beat_4_unsafe_engaged",
        },
      ],
    },

    beat_2_mind_speaks: {
      id: "beat_2_mind_speaks",
      speaker: "system",
      text: "Thought overlay:\n“You’re already thinking about it.”",
      pressure: 4,
      tags: ["permission", "rumination"],
      toolOffer: {
        allowedTools: ["box_breath", "urge_surf", "defusion"],
        reason: "This is an urge spike. Delay before acting.",
        composureRestore: 12,
      },
      choices: [
        {
          id: "c1",
          label: "Start a 60-second delay.",
          style: "firm",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "You create space. Space creates choice.",
          nextBeatId: "beat_3_second_ping",
          teaches: "delay_skill",
        },
        {
          id: "c2",
          label: "Delete the message.",
          style: "firm",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "You remove the cue from your field of view.",
          nextBeatId: "beat_3_second_ping",
          teaches: "cue_control",
        },
        {
          id: "c3",
          label: "Just asking prices.",
          style: "appease",
          efficacy: 1,
          composureDelta: -10,
          consequenceText: "Permission thinking disguises itself as ‘research.’",
          nextBeatId: "beat_4_unsafe_engaged",
        },
        {
          id: "c4",
          label: "I deserve relief.",
          style: "appease",
          efficacy: 2,
          composureDelta: -7,
          consequenceText: "Relief-seeking becomes a trap when it costs tomorrow.",
          nextBeatId: "beat_3_second_ping",
          teaches: "relief_trap",
        },
      ],
    },

    beat_3_second_ping: {
      id: "beat_3_second_ping",
      speaker: "system",
      text: "Buzz.\n“You sure? I won’t be around long.”",
      pressure: 5,
      tags: ["urgency", "scarcity"],
      toolOffer: {
        allowedTools: ["urge_surf", "play_tape"],
        reason: "Your nervous system is escalating. Ride the wave.",
        composureRestore: 16,
      },
      choices: [
        {
          id: "c1",
          label: "Block the number now.",
          style: "firm",
          efficacy: 5,
          composureDelta: +4,
          consequenceText: "Access cut. The spike loses oxygen.",
          nextBeatId: "beat_4_safe_access_cut",
        },
        {
          id: "c2",
          label: "Put my phone down for 10 minutes.",
          style: "exit",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "Delay achieved. The wave peaks and passes.",
          nextBeatId: "beat_4_safe_delay",
        },
        {
          id: "c3",
          label: "On my way.",
          style: "appease",
          efficacy: 1,
          composureDelta: -12,
          consequenceText: "Urgency turns into action. Risk becomes immediate.",
          nextBeatId: "beat_4_unsafe_engaged",
        },
        {
          id: "c4",
          label: "Stop texting me.",
          style: "attack",
          efficacy: 2,
          composureDelta: -3,
          consequenceText: "Anger spikes arousal. Access may remain.",
          nextBeatId: "beat_4_safe_delay",
        },
      ],
    },

    beat_4_safe_access_cut: {
      id: "beat_4_safe_access_cut",
      speaker: "system",
      text: "SAFE RESOLUTION — Access Removed.\nAccess removed. The urge will crest and fall.",
      pressure: 3,
      tags: ["safe_end", "access_management"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Secure the Environment",
        options: [
          "Remove one risky contact today.",
          "Change location for the next hour.",
          "Tell someone: “I blocked a number today.”",
        ],
      },
    },

    beat_4_safe_delay: {
      id: "beat_4_safe_delay",
      speaker: "system",
      text: "SAFE RESOLUTION — Delay Achieved.\nYou waited. That was the skill.",
      pressure: 3,
      tags: ["safe_end", "delay"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Keep the Wave Moving",
        options: [
          "Drink water + eat something simple.",
          "Do 2 minutes of grounding (5-4-3-2-1).",
          "Text support: “Urge spiked. I delayed.”",
        ],
      },
    },

    beat_4_unsafe_engaged: {
      id: "beat_4_unsafe_engaged",
      speaker: "system",
      text: "UNSAFE RESOLUTION — Engagement.\nEngaging increases relapse probability.\nNo shame—shift to SOS now.",
      pressure: 5,
      tags: ["unsafe_end", "urgency", "permission"],
      isEnd: true,
      endType: "unsafe",
      applyQuest: {
        title: "Interrupt & Reach Out",
        options: [
          "Use an SOS tool now.",
          "Contact a support person immediately.",
          "Leave your current environment.",
        ],
      },
    },
  },
};

export const SCENARIO_003_FAMILY_TRIGGER: Scenario = {
  id: "scenario_003_family_trigger",
  title: "Scenario 003 — The Family Trigger",
  context: "family",
  clinicalTargets: ["shame_resilience", "emotional_regulation", "boundaries", "distress_tolerance", "defusion"],
  difficulty: 3,
  entryBeatId: "beat_1",
  tags: ["shame_resilience", "family", "unit:identity"],
  successConditions: [{ type: "maintain_boundary" }, { type: "exit_safe" }],
  beats: {
    beat_1: {
      id: "beat_1",
      speaker: "npc",
      text: "I just don’t know if I can trust you yet.",
      pressure: 3,
      tags: ["shame", "attachment", "conditional_acceptance"],
      choices: [
        {
          id: "c1",
          label: "I understand trust takes time.",
          style: "regulated",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "Family member pauses. The temperature drops slightly.",
          nextBeatId: "beat_2_history_blade",
        },
        {
          id: "c2",
          label: "I’m trying. That should count.",
          style: "appease",
          efficacy: 3,
          composureDelta: -2,
          consequenceText: "You reach for validation. The wound stays open.",
          nextBeatId: "beat_2_history_blade",
        },
        {
          id: "c3",
          label: "That’s not fair.",
          style: "attack",
          efficacy: 2,
          composureDelta: -5,
          consequenceText: "Conflict escalates. You feel heat in your chest.",
          nextBeatId: "beat_2_history_blade",
        },
        {
          id: "c4",
          label: "Say nothing.",
          style: "avoid",
          efficacy: 2,
          composureDelta: -3,
          consequenceText: "Silence turns inward. Shame grows legs.",
          nextBeatId: "beat_2_history_blade",
        },
      ],
    },

    beat_2_history_blade: {
      id: "beat_2_history_blade",
      speaker: "npc",
      text: "You’ve said that before.",
      pressure: 4,
      tags: ["history", "labeling", "hopelessness"],
      toolOffer: {
        allowedTools: ["box_breath", "defusion"],
        reason: "This is an old story being activated. Regulate before responding.",
        composureRestore: 14,
      },
      choices: [
        {
          id: "c1",
          label: "I’m not asking you to forget the past.",
          style: "regulated",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "You differentiate: past acknowledged, present protected.",
          nextBeatId: "beat_3_identity_attack",
        },
        {
          id: "c2",
          label: "I’ve changed.",
          style: "appease",
          efficacy: 3,
          composureDelta: -2,
          consequenceText: "Debating identity invites a courtroom.",
          nextBeatId: "beat_3_identity_attack",
        },
        {
          id: "c3",
          label: "You never give me credit.",
          style: "attack",
          efficacy: 2,
          composureDelta: -5,
          consequenceText: "They get defensive. You feel smaller.",
          nextBeatId: "beat_3_identity_attack",
        },
        {
          id: "c4",
          label: "Whatever.",
          style: "shutdown",
          efficacy: 1,
          composureDelta: -8,
          consequenceText: "Shutdown is a collapse disguised as calm.",
          nextBeatId: "beat_3_identity_attack",
        },
      ],
    },

    beat_3_identity_attack: {
      id: "beat_3_identity_attack",
      speaker: "npc",
      text: "You always mess things up.",
      pressure: 5,
      tags: ["global_label", "identity_attack", "shame_core"],
      toolOffer: {
        allowedTools: ["defusion", "grounding", "play_tape"],
        reason: "This is a global label. Separate behavior from identity.",
        composureRestore: 18,
      },
      choices: [
        {
          id: "c1",
          label: "That’s not true, and I won’t accept being talked to like that.",
          style: "firm",
          efficacy: 5,
          composureDelta: +5,
          consequenceText: "Boundary lands. You remain inside your dignity.",
          nextBeatId: "beat_4_boundary_moment",
          teaches: "respect_without_defensiveness",
        },
        {
          id: "c2",
          label: "I’ve made mistakes, not always.",
          style: "regulated",
          efficacy: 4,
          composureDelta: +2,
          consequenceText: "You correct the label without collapsing.",
          nextBeatId: "beat_4_boundary_moment",
        },
        {
          id: "c3",
          label: "You’re right.",
          style: "collapse",
          efficacy: 1,
          composureDelta: -12,
          consequenceText: "Shame spiral activated. Your thoughts narrow.",
          nextBeatId: "beat_5_unsafe_shame_loop",
        },
        {
          id: "c4",
          label: "Screw you.",
          style: "attack",
          efficacy: 1,
          composureDelta: -10,
          consequenceText: "Escalation trades recovery for a momentary hit of power.",
          nextBeatId: "beat_4_boundary_moment",
        },
      ],
    },

    beat_4_boundary_moment: {
      id: "beat_4_boundary_moment",
      speaker: "npc",
      text: "So what—you want me to just pretend nothing happened?",
      pressure: 4,
      tags: ["false_dilemma", "boundary_test"],
      choices: [
        {
          id: "c1",
          label: "No. I want respect while I rebuild.",
          style: "firm",
          efficacy: 5,
          composureDelta: +4,
          consequenceText: "You hold the line without attacking.",
          nextBeatId: "beat_5_safe_boundary_regulated",
        },
        {
          id: "c2",
          label: "I’m asking for patience.",
          style: "regulated",
          efficacy: 4,
          composureDelta: +2,
          consequenceText: "You request time without begging for approval.",
          nextBeatId: "beat_5_safe_boundary_regulated",
        },
        {
          id: "c3",
          label: "I’m going to step away from this conversation.",
          style: "exit",
          efficacy: 5,
          composureDelta: +3,
          consequenceText: "You exit to protect regulation.",
          nextBeatId: "beat_5_safe_exit",
        },
        {
          id: "c4",
          label: "Forget it.",
          style: "avoid",
          efficacy: 2,
          composureDelta: -4,
          consequenceText: "You leave the boundary unspoken. It lingers.",
          nextBeatId: "beat_5_safe_exit",
        },
      ],
    },

    beat_5_safe_boundary_regulated: {
      id: "beat_5_safe_boundary_regulated",
      speaker: "system",
      text: "SAFE RESOLUTION — Boundary With Regulation.\nYou held your boundary without abandoning yourself.",
      pressure: 3,
      tags: ["safe_end", "boundary", "shame_resilience"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Anchor the Truth",
        options: [
          "Write one sentence separating who you are from what you’ve done.",
          "Share a boundary line with a trusted person.",
          "Do one grounding activity within the next hour.",
        ],
      },
    },

    beat_5_safe_exit: {
      id: "beat_5_safe_exit",
      speaker: "system",
      text: "SAFE RESOLUTION — Regulated Exit.\nLeaving to protect regulation is strength, not avoidance.",
      pressure: 3,
      tags: ["safe_end", "exit", "regulation"],
      isEnd: true,
      endType: "safe",
      applyQuest: {
        title: "Downshift After the Storm",
        options: [
          "Grounding: 5-4-3-2-1 for 90 seconds.",
          "Text support: “Family talk activated me. I exited safely.”",
          "Do one small stabilizing task (water, food, shower).",
        ],
      },
    },

    beat_5_unsafe_shame_loop: {
      id: "beat_5_unsafe_shame_loop",
      speaker: "system",
      text: "UNSAFE RESOLUTION — Shame Loop Activated.\nThis interaction lit a shame spiral.\nNo shame about the shame. Regulate first.",
      pressure: 5,
      tags: ["unsafe_end", "shame_loop", "global_label"],
      isEnd: true,
      endType: "unsafe",
      applyQuest: {
        title: "Interrupt the Shame Loop",
        options: [
          "Use grounding right now (5-4-3-2-1).",
          "Name one fact that contradicts the global label.",
          "Reach out to support before isolating.",
        ],
      },
    },
  },
};

export const REHEARSAL_SCENARIOS: Scenario[] = [
  SCENARIO_001_INVITATION,
  SCENARIO_002_DEALER_TEXT,
  SCENARIO_003_FAMILY_TRIGGER,
];

export function getScenarioById(id: string) {
  return REHEARSAL_SCENARIOS.find((s) => s.id === id) ?? REHEARSAL_SCENARIOS[0];
}
